### ISSUE TITLE
xattr option -x on MacOS 12/2 throws an error when running exiftool

### ISSUE THREAD

**Issue by oPromessa** [xattr/xattr#101]
Hi there. Excellent tool. Congrats. 

I ran into the following issue:
- running exiftool on Mac OS 12.2
- using exiftool which calls "xattr -lx" at some point to get extended attributes. 
   - https://github.com/exiftool/exiftool/blob/00e4fdc52ea3780e25b0371e9817ecb39329518c/lib/Image/ExifTool/MacOS.pm#L568-L571
- /usr/bin/xattr does recognize the -x option
- but if I have python xattr module installed, which does not recognize the -x option; 
- exiftool finds xattr from local/bin instead of the system one and throws a warning/error
- indicating failure to access extended attributes

Is it possible to make this module compatible with the -x option?

Thanks in advance for your support.

**Comment by etrepum** [comment]
I'm not sure when I would have time to look at this, but if someone else is interested it looks like this is where Apple keeps their fork and patches: https://opensource.apple.com/source/python_modules/python_modules-61.140.1/Modules/xattr-0.6.4/
