### ISSUE TITLE
Readme file request - why this python xattr rather than attr package's getfattr/setfattr etc?

### ISSUE THREAD

**Issue by akira-kurogane** [xattr/xattr#102]
Hi. I was reinstalling a cmdline tool to manually check the extended filesystem attributes in some datastore thing I was I developing.

I'd forgotten what the command was called however. Googling for "xattr" takes you all over the place. A lot of people who are searching for the right linux man page will end up here instead.

What I wanted, when I finally found them, were the [getfattr](https://man7.org/linux/man-pages/man1/getfattr.1.html), [setfattr](https://man7.org/linux/man-pages/man1/setfattr.1.html) in the [attr](http://savannah.nongnu.org/projects/attr) package. That's the shortest distance between the commandline user (me) and using the setxattr, getxattr, listxattr and removexattr syscalls.

But I'm curious as to what the purpose of this packaged python script is. Is it that getfattr etc. isn't available on OSX even though it also supports extended filesystem attributes? (with quirks?)

And could that please be put in the README.md?

**Comment by etrepum** [comment]
Those tools were not available on macOS at the time. Not sure if they are now or not, but Apple actually shipped this tool with macOS until recently.

A PR to add the sort of information you'd like to see would be the quickest way to get this done, I'd be happy to review and merge.

**Comment by akira-kurogane** [comment]
Thanks Bob. Sounds good to me. I've created a PR which is has become issue #103. I'll close this issue.
