### ISSUE TITLE
package doesn't install `lib_build.h`

### ISSUE THREAD

**Issue by Chichilele** [xattr/xattr#108]
Installing `xattr` on a fresh python environment on MacOS 12.6 works but library throws an error on import. It breaks poetry which has a dependency on xattr (see [this issue](https://github.com/python-poetry/poetry/issues/6891))

Steps to reproduce (on a fresh python 3.8.13 environment):
1. `pip install xattr`
2. `python -c 'import xattr'
```python
Traceback (most recent call last):
  File "/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/xattr/lib.py", line 7, in <module>
    from ._lib import lib, ffi
ImportError: dlopen(/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 0x0002): Library not loaded: '@rpath/libffi.8.dylib'
  Referenced from: '/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so'
  Reason: tried: '/Users/gauthiercastro/miniconda3/envs/speccheck_eval/lib/libffi.8.dylib' (no such file), '/Users/gauthiercastro/miniconda3/envs/speccheck_eval/lib/libffi.8.dylib' (no such file), '/Users/gauthiercastro/miniconda3/envs/speccheck_eval/lib/libffi.8.dylib' (no such file), '/Users/gauthiercastro/miniconda3/envs/speccheck_eval/lib/libffi.8.dylib' (no such file), '/opt/homebrew/lib/libffi.8.dylib' (no such file), '/opt/homebrew/lib/libffi.8.dylib' (no such file), '/opt/homebrew/lib/libffi.8.dylib' (no such file), '/opt/homebrew/lib/libffi.8.dylib' (no such file), '/opt/homebrew/lib/libffi.8.dylib' (no such file), '/opt/homebrew/lib/libffi.8.dylib' (no such file), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/xattr/__init__.py", line 13, in <module>
    from .lib import (XATTR_NOFOLLOW, XATTR_CREATE, XATTR_REPLACE,
  File "/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/xattr/lib.py", line 9, in <module>
    from .lib_build import ffi, c_source
  File "/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/xattr/lib_build.py", line 7, in <module>
    with open(os.path.join(PATH, 'lib_build.h')) as hf:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/xattr/lib_build.h'
```

Any idea what could be wrong?

**Comment by etrepum** [comment]
It looks like your installation of cffi is broken or corrupted somehow, which causes the xattr import to fail and fall back to trying to build the extension which won't work. lib_build.h is only used when building the extension. There's nothing really that can be done from xattr's perspective here.

**Comment by phdowling** [comment]
This is still causing issues for me, I'm using an M2 Mac. Tried reinstalling xattr, cffi as well as my entire python environment but `python -c "import xattr"` still fails:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dowling/.pyenv/versions/3.12.0/lib/python3.12/site-packages/xattr/__init__.py", line 13, in <module>
    from .lib import (XATTR_NOFOLLOW, XATTR_CREATE, XATTR_REPLACE,
  File "/Users/dowling/.pyenv/versions/3.12.0/lib/python3.12/site-packages/xattr/lib.py", line 9, in <module>
    from .lib_build import ffi, c_source
  File "/Users/dowling/.pyenv/versions/3.12.0/lib/python3.12/site-packages/xattr/lib_build.py", line 7, in <module>
    with open(os.path.join(PATH, 'lib_build.h')) as hf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dowling/.pyenv/versions/3.12.0/lib/python3.12/site-packages/xattr/lib_build.h'
```

Installed xattr version: 0.10.0
Install cffi version: 1.16.0

Any ideas?

**Comment by etrepum** [comment]
If you post full instructions to reproduce your issue, particularly how you installed python and what commands you ran to get your installation into this state, I will look into it. Is there a reason why you are attempting to use 0.10.0 instead of 0.10.1?

**Comment by samuelchrist** [comment]
I am using poetry on M1 mac os Sonoma. Tried reinstalling poetry, xattr, cffi as well as my entire python environment but python -c "import xattr" still fails:

I am using xattr 0.10.1

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/venv/lib/python3.8/site-packages/xattr/__init__.py", line 13, in <module>
    from .lib import (XATTR_NOFOLLOW, XATTR_CREATE, XATTR_REPLACE,
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/venv/lib/python3.8/site-packages/xattr/lib.py", line 9, in <module>
    from .lib_build import ffi, c_source
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/venv/lib/python3.8/site-packages/xattr/lib_build.py", line 7, in <module>
    with open(os.path.join(PATH, 'lib_build.h')) as hf:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/Library/Caches/pypoetry/virtualenvs/venv/lib/python3.8/site-packages/xattr/lib_build.h'
```
Please help

**Comment by samuelchrist** [comment]
> I don't know why you're having an issue with Python 3.8, but it does seem like Python 3.12 causes some serious problems with the build as it has removed a bunch of functionality that is required by the current build process and cffi version. Will probably be a few days at least until that can be sorted out, unless someone else wants to contribute.

Even I am not sure but i see there is some issue with this while using poetry. Can you help to understand what could be the root cause.? Are you able to replicate the issue. ?

**Comment by etrepum** [comment]
I have no experience using poetry, you may want to ask them.

My top priority will be addressing Python 3.12 support, but I have limited time to work on it right now. If anyone has the experience and time to contribute I'd be happy to review PRs. I will look into poetry and Python 3.8 after Python 3.12 is supported, whenever that happens.

**Comment by phdowling** [comment]
Sorry for the late response, will try to put more detailed steps to reproduce tomorrow, but basically I think it was:

- uninstall all python versions from the system
- Install pyenv
- Install 3.12 via pyenv
- pip install xattrs
- import xattr fails as outlined in my last comment

I sort of got it to work by manually putting the missing .h and .c files into the appropriate site_packages directory, but I was still left unable to use poetry. Used a manual virtualenv + pip for now but that is not really a good permanent solution for me.

**Comment by etrepum** [comment]
It sounds like poetry is part of the problem in all of these cases, perhaps you should bring it up with that project

**Comment by etrepum** [comment]
I cut a new release that removes usage of deprecated setuptools/distutils/cffi features and should at least have a different error message if the extension wasn't installed. It builds and installs correctly with Python 3.12 on all platforms and architectures that cibuildwheel works with.
