### ISSUE TITLE
x86_64 wheels for macOS 11.0+

### ISSUE THREAD

**Issue by RhetTbull** [xattr/xattr#113]
[Wheels for xattr](https://pypi.org/project/xattr/0.10.1/#files) on macOS 11+ are only available for `arm_64` architecture. Wheels on earlier versions of macOS are available for `x86_64` and `universal2`.  This effectively means that xattr cannot be installed on Intel Macs running Big Sur or later without also installing the [XCode command line](https://developer.apple.com/xcode/resources/) tools to build from source.  For regular users who haven't done this trying to install something that has xattr as a dependency, this [causes `pipx` to fail](https://github.com/RhetTbull/osxphotos/discussions/1204).  A workaround is to install the older wheel manually but this is not ideal.

Is it possible to get `x86_64` wheels built for newer macOS versions?

**Comment by alex** [comment]
macOS versions in wheel specifiers indicate the minimum version, and they can be installed with newer versions of macOS, and pip will do so.

**Comment by RhetTbull** [comment]
That's what I thought but I've had 2 reports in the last week of users trying to use `pipx` to install [a package I maintain](https://github.com/RhetTbull/osxphotos) report an error using `pipx` related to xattr. It appears to me the issue is that `pipx` is trying to build xattr instead of grabbing the x86 wheel.

```
pip failed to build package:
xattr

..
.error: subprocess-exited-with-error
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
error: command '/usr/bin/clang' failed with exit code 1
```

**Comment by RhetTbull** [comment]
Did some more digging. The package which includes the `xattr` dependency has an old version of `wheel` pinned (`^0.37.1`). Current version of `wheel` is `0.41.2`. Nothing in the [CHANGELOG](https://wheel.readthedocs.io/en/stable/news.html) jumps out at me but I wonder if the older version of `wheel` has something to do this with. I'll see if I can recreate the issue using `--only-binary` option on `pip`and the older version of `wheel`. I have access to an Intel Mac running Ventura which is where the problem is manifesting.

**Comment by RhetTbull** [comment]
I figured this out. The issue is the dependency was pegged to `xattr==0.9.9` but user was installing with python 3.11. There is no xattr 0.9.9 wheel for python 3.11 and thus pip was trying to build from source which fails on macOS if user doesn't have the Xcode command line tools install. Fortunately I maintain the package that has xattr dependency so I can update this. Sorry about the confusion.

**Comment by etrepum** [comment]
Thank you for the thorough investigation and follow-up!
