### ISSUE TITLE
FreeBSD compatibility problems

### ISSUE THREAD

**Issue by Jamie-Landeg-Jones** [xattr/xattr#116]
From what I can gather, linux uses the prefix "user." in the attribute name to specify the user namespace.

FreeBSD specifies the namespace in a different place (as you can see in your code here:)

---
return extattr_get_file(path, EXTATTR_NAMESPACE_USER,
                                name, value, size);
---

This has meant that any xattrs set via this library have the needless prefix "user". This hasn't really been a problem up until now, but in trying to get extattrs to be compatible between Linux and FreeBSD with a common ZFS filesystem, to avoid ambiguity, the ZFS folks have blocked any FreeBSD attributes starting with "user."

This basically means that on any recent FreeBSD system, xattrs no longer work for ZFS filesystems.

This is much more clearly described here: https://github.com/openzfs/zfs/commit/5c0061345b824eebe7a6578528f873ffcaae1cdd

So, could the "user." prefix be filtered out when setting external attributes on freebsd?

As an aside, whilst at first glance it may seem an idea to drop any other prefixes apart from "system." which on freebsd would be used with extattr_set/get as EXTATTR_NAMESPACE_SYSTEM", the use of the system namespace is different. Linux appears to use the system namespace to store all sorts of other attributes, like ACL's, whilst Freebsd stores ACLS elsewhere.

So, I'd suggest just removing the "user." if it exists, and leaving anything else "as is".

Does this sound reasonable?

Cheers, Jamie

**Comment by Jamie-Landeg-Jones** [comment]
Hi. I agree that an API with a separate namespace parameter would be neatest - then we wouldn't need to needlessly strip "user" off a  FreeBSD xattr name, if the user really, really had wanted it, something I'm not entirely comfortable with.

However,  as you say, FreeBSD is the outlier here, so the simpler solution would be to go with your suggestion, especially as the ZFS folk have effectively banned extattrs beginning with "user." on FreeBSD now (the reason I noticed this is migrating a filesystem to a different machine running a newer freebsd version, and my files that contained xattrs via your library now produce errors when copying, and fail to set the values)

So, your suggestion is easily the clearest and best option, in my opinion. I did notice you had some freebsd conditionals in your code already, in file  lib_build.c . Maybe in function "void convert_bsd_list"

As for the PR, yeah, I can do that. I only raised it here because I saw the FreeBSD code here, but are you saying this was an external contribution? If so, sorry for the noise, and yes, I can sort this out with the FreeBSD maintainer, who will presumably request to upstream it here.

Thanks for your help and quick response,
Cheers, Jamie

**Comment by etrepum** [comment]
I'm not so sure anyone is actively maintaining the FreeBSD support. Looks like the initial patch to add FreeBSD landed in 2006 (by someone who I'm pretty sure doesn't do much Python anymore) and the last FreeBSD fix was in 2015 😉 I am not sure I have ever personally tested the FreeBSD build, certainly not in the past decade or so.

**Comment by Jamie-Landeg-Jones** [comment]
Ah ok, well, I'm not officially part of the FreeBSD core team, but I am quite active, and maintain a few ports there.

I know that the port there still works, but I notice it's not been updated since 0.9.8 - I'll have a go at updating it and fixing this issue, and I'll post any freebsd changes here if you want. If you'd prefer, I can just keep the changes local to the freebsd port/package, but as I see you already have ifdef's for freebsd, it may be neater to incorporate them here, under the appropriate ifdefs.

Your call, of course.

**Comment by Jamie-Landeg-Jones** [comment]
... or, if you want to remove the FreeBSD bits from your tree, I can instead move them into the local port patch system.

**Comment by etrepum** [comment]
I think it would be ideal to keep it all here rather than patched maintained separately in the ports tree, but happy to support whatever makes things easier for you.

**Comment by Jamie-Landeg-Jones** [comment]
I think that that's definitely the best option - I just wondered that maybe as you said that you aren't a FreeBSD user, and don't have a FreeBSD test system, and the FreeBSD code hasn't been actively been maintained, that you may have preferred clearing it out rather than having it modified. I would have been happy to help either way.

Anyway, cheers. I'll have a look at it soon and get back to you. Hopefully the latest version applies cleanly :-)

**Comment by novel** [comment]
> I notice it's not been updated since 0.9.8 - I'll have a go at updating it and fixing this issue

Looking forward to your changes.

// FreeBSD maintainer

**Comment by etrepum** [comment]
I'd also be happy to add FreeBSD to the CI suite if you can point me in the right direction for how that's typically done these days. Looks like there's https://github.com/vmactions/freebsd-vm - but it's been maybe 15 years since I've spent much time with FreeBSD so I could use some pointers if you have any

**Comment by novel** [comment]
Unfortunately, I don't have experience with the Github CI and the freebsd-vm project.
However, I was able to find an example with freebsd-vm: https://github.com/giampaolo/psutil/blob/master/.github/workflows/bsd.yml.

I guess the workflow doesn't differ too much from Linux, except that packages are installed using the `pkg` package manager. Required packages (I think) for building and testing xattr on FreeBSD would be: `py39-cffi py39-setuptools py39-pytest`.

**Comment by Jamie-Landeg-Jones** [comment]
Apologies for the delay in replying.. Real life got in the way!

I've completed the patch.. I guess now I have to figure out git!

The "get" and "set" work more or less as you expected. The "list" function was a bit more involved, as the normal flow of events is to call list with a NULL return buffer - in this case, list_xattr returns just the length of the result. So the calling program them mallocs the appropriate space, and calls list_xattr again with this allocated buffer which then gets the results filled in.

However, in this case, the length of the buffer is bigger (number of entries * 5) [i.e. number of entries * length of "user."), so we need to actually exctract the list into a temporary buffer, count the entries, and return the new length value)

Anyway, let me know of any issues, such as formatting, or places where more comments could be useful etc.

The tests all pass, too:

# python3.10 /usr/local/lib/python3.10/site-packages/xattr/tests/__init__.py
..........sssss...
----------------------------------------------------------------------
Ran 18 tests in 0.046s

OK (skipped=5)

Cheers, Jamie (I guess a pull request is the best way to submit this, or can i post a diff file here?)

**Comment by Jamie-Landeg-Jones** [comment]
> I'd also be happy to add FreeBSD to the CI suite if you can point me in the right direction for how that's typically done these days.

Unfortunately, I know little about git and github, and even less about CI integration.

**Comment by etrepum** [comment]
A diff would be fine, I'm happy to create the PR from that if it's easier for you

**Comment by Jamie-Landeg-Jones** [comment]
Thanks. I do need to start looking at git - just about everywhere uses it these days!

As for the PR, do you mean the PR on the FreeBSD site? I'm fine doing that part, it's just the git/github bit I'm not familiar with!

Anyway, the diff should be attached here!
[patch-lib_build.c.patch](https://github.com/xattr/xattr/files/14111608/patch-lib_build.c.patch)

**Comment by Jamie-Landeg-Jones** [comment]
Thanks! Ok, I get it now, "PR" - "Pull request". I was thinking of FreeBSDs "problem report" system for updating ports etc.

Sorry for the confusion!

Are you able to tag a new release? That will make it easier to update the FreeBSD port.

Cheers, Jamie

**Comment by etrepum** [comment]
Absolutely, I will tag a release once it's merged! Should be this week.

**Comment by Jamie-Landeg-Jones** [comment]
Great! Thanks for your help with this. You've been most helpful, patient, and accommodating.

👍

**Comment by etrepum** [comment]
#117 should merge after the next CI test suite runs and then I'll tag and release later this evening

**Comment by Jamie-Landeg-Jones** [comment]
FreeBSD PR for ports tree raised:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276964

**Comment by etrepum** [comment]
Great, thank you @Jamie-Landeg-Jones!
