### ISSUE TITLE
xattr vs os xattr methods?

### ISSUE THREAD

**Issue by pjotrek-b** [xattr/xattr#121]
I just found this:
https://docs.python.org/3/library/os.html#linux-extended-attributes

I always like to keep my code as close to vanilla dependencies as possible, so when would I use your xattr library, and when the methods provided by `os`?

Thank you for insights :smile:

**Comment by etrepum** [comment]
I don't know, these came much later than the development of this package. It might be that if you're using a recent version of Python you may not need this dependency. Why not try it and see if it suits your needs.

**Comment by pjotrek-b** [comment]
@etrepum: Roger that. Good to know!

Indeed, I've tried xattr-methods of `pyton.os` - and so far they work perfectly fine (tried get/set/list/remove).

**Comment by jmberg** [comment]
Python can be tricky with non-utf-8, e.g. listxattr() says it returns fs-encoded strings.

It works for me now on python 3.12, but I'd check with the lowest python version you want to support.

**Comment by pjotrek-b** [comment]
@jmberg : Thanks for the remarks!
I haven't tested outside of UTF-8 yet.
Next on my list is handling embedded byte-code (thumbnail images) as xattrs, so I may know more then...
