### ISSUE TITLE
Can xattr install in Windows OS?

### ISSUE THREAD

**Issue by zhaozhiming** [xattr/xattr#17]
when I use pip or easy_install to install xattr in my win7, it always get wrong. 
Can xattr install in Windows OS? Thank you.

**Comment by petersilva** [comment]
I understand that it doesn´t work, but the distutils packaging should say so, and prevent itself from installing.  I made a package that briefly had xattr as a dependency and on windows it blithely tries to install it.  Result:

>>>>        C:\Program Files (x86)\Microsoft Visual Studio
>>>> 10.0\VC\BIN\amd64\cl.exe /c /
>>>> nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python34\include
>>>> -Ic:\python34\include /Tc
>>>> build\temp.win-amd64-3.4\Release\_lib.c
>>>> /Fobuild\temp.win-amd64-3.4\Release\buil
>>>> d\temp.win-amd64-3.4\Release\_lib.obj
>>>>        _lib.c
>>>>        build\temp.win-amd64-3.4\Release\_lib.c(433) : fatal error
>>>> C1083:
>>>> Cannot ope
>>>> n include file: 'sys/xattr.h': No such file or directory
>>>>        error: command 'C:\\Program Files (x86)\\Microsoft Visual

now trying to install anything else, it tries to fix xattr, and the whole python environment is hosed as a result.  There should be something in distuils to fail much more cleanly than it does

**Comment by etrepum** [comment]
@petersilva It sounds like your issue is with distutils, perhaps you should bring it up in the appropriate channel. xattr does not claim any Windows support in its distutils metadata or anywhere else.

**Comment by petersilva** [comment]
OK, I opened this: https://github.com/pypa/setuptools/issues/1602

**Comment by petersilva** [comment]
I looked through setuptools docs and I could find information about making dependencies vary by platform, but I can't find anything in the grammar to say that a package is fundamentally not compatible with an OS.
I would think the *platform* declaration already present would give a good clue, but apparently not.

**Comment by merwok** [comment]
distutils (or setuptools) does not really have a concept of restricting by platform.

To discuss this problem, I suggest using a not the issue tracker of one tool but a standards discussion forum: https://discuss.python.org/c/packaging/14
