### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by asmeurer** [xattr/xattr#20]
Python 3 does not work, because of the print statements in tool.py. I didn't see if there are other incompatibilities as well, though assumedly there aren't many since Python 3 is listed as supported in setup.py. 

You should add `from __future__ import print_function` to the top of every file to avoid this in the future.

**Comment by M0rtenB** [comment]
Line 80 in __init__.py throws a
TypeError: 'float' object cannot be interpreted as an integer
when using hex_to_hash in Python 3, because of the division symbol.

**Comment by etrepum** [comment]
@M0rtenB do you mind sending a PR for this issue, at least to add a test for it?

**Comment by ThomasWaldmann** [comment]
OK, so this issue says Python 3 does not work, but the package metadata says:
```
Programming Language :: Python :: 3
```

So, what's correct?

Also, if that's getting fixed, I'ld like to suggest to be more precise about which specific python X.X versions are supported.

**Comment by etrepum** [comment]
Python 3 is supposed to work. Someone said it did not, but nobody has sent in enough information to reproduce the issue.
