### ISSUE TITLE
bup needs xattr.get_all()

### ISSUE THREAD

**Issue by jmberg** [xattr/xattr#34]
This is the reason it wants to use python-pyxattr, it's probably easy to re-implement that?

Right now I have a conflict between bup and calendarserver, which is really annoying.

Thoughts? I might take a stab at it but am unfamiliar with all of this. Perhaps somebody else already took a look?

**Comment by etrepum** [comment]
I haven't seen any other reports of this. You should give it a shot, I suspect it's just another name for something that's already here. If you send a pull request I'll review and likely accept it.

**Comment by jmberg** [comment]
Given the UTF-8 incompatibility, there's little point in having xattr provide it. I've written a compatibility module that side-steps that issue, but then this clearly isn't needed.
