### ISSUE TITLE
refuses to work with non-utf8 keys

### ISSUE THREAD

**Issue by jmberg** [xattr/xattr#36]
I'm not sure why xattr explicitly treats keys as utf-8, but clearly that's not necessarily the case.

```bash
$ attr -g "$(echo -en 'x\xff')" x
Attribute "x�" had a 8 byte value for x:
asdfjkl;
```

but python-xattr fails:
```python
>>> xattr.xattr('x').items()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johannes/Projects/bup/xattr/xattr/__init__.py", line 170, in items
    return list(self.iteritems())
  File "/home/johannes/Projects/bup/xattr/xattr/__init__.py", line 166, in iteritems
    for k in self.list():
  File "/home/johannes/Projects/bup/xattr/xattr/__init__.py", line 98, in list
    return [s.decode('utf-8') for s in res]
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 6: invalid start byte
```

I'd suggest to just remove the erroneous utf-8 decoding, but that could make the library backwards incompatible? OTOH, it will make it more compatible with python-pyxattr which supports that.

(this, btw, will mean bup cannot support using python-xattr, as clearly a backup tool must not fail when reading xattrs)

**Comment by etrepum** [comment]
On Mac OS X, where xattr was originally developed, utf-8 key names are mandated. For backward compatibility's sake, it would be better to have a `blist` method or something like that to get the list as bytes.

**Comment by jmberg** [comment]
Interesting, I had no idea.

Fair enough - I'll give up trying to make xattr and pyxattr compatible in any way.
