### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by novel** [xattr/xattr#39]
It would be great to have a new release that would include this FreeBSD fix: https://github.com/xattr/xattr/commit/798568b06131d49e581e7185b41c24d550b1bbe0 and that will be available on pypi.
It will ease venv setups on FreeBSD.

**Comment by etrepum** [comment]
v0.7.7 is out

**Comment by etrepum** [comment]
Thanks!

**Comment by novel** [comment]
Thanks a lot!
