### ISSUE TITLE
0.7.7: missing some .txt files in release tarballs

### ISSUE THREAD

**Issue by novel** [xattr/xattr#40]
The 0.7.7 tarball (as downloaded from pypi) misses some useful .txt files (e.g. LICENSE.txt) that were present in 0.7.5:

(19:42) novel@kloomba:~/pyxattr %> ls xattr-0.7.7|grep -e "txt$"
README.txt
(19:43) novel@kloomba:~/pyxattr %> ls xattr-0.7.5|grep -e "txt$"
CHANGES.txt
INSTALLING.txt
LICENSE.txt
README.txt
TODO.txt
requirements.txt
(19:43) novel@kloomba:~/pyxattr %>

I'm not sure if all of them are needed, but LICENSE.txt is nice to have from distro packaging point of view.

Thanks

**Comment by etrepum** [comment]
Must be a setuptools issue or something, certainly not something that was explicitly changed. Ugh.

**Comment by novel** [comment]
Thanks!
