### ISSUE TITLE
xattr -l <file-with-no-attributes> outputs nothing

### ISSUE THREAD

**Issue by devinlane** [xattr/xattr#53]
This makes it difficult to see files that _don't_ have any attributes when listing other files that do. For example, assuming files a, b, and d have attributes while c and e do not:

```
> xattr -l a b c d e
a: user.attr: a
b: user.attr: b
d: user.attr: d
```

Note that nothing is printed for c and e. I propose that xattr should instead produce output that looks like this:

```
a: user.attr: a
b: user.attr: b
c:
d: user.attr: d
e:
```

I would further suggest using an '=' instead of a ':' for the attribute value ("user.attr = a") to make the output easier to parse. This would then appear as:

```
a: user.attr=a
b: user.attr=b
c:
d: user.attr=d
e:
```

**Comment by devinlane** [comment]
(Happy to implement this of course, just want some feedback)

**Comment by Glandos** [comment]
Or a keyword such as "none"? May not be the best idea, just brainstorming here.

**Comment by devinlane** [comment]
None would work as well. Basically, since this is a developer tool, I want to make its output easy to feed into other commands. So being able to do `xattr -l * | grep -v =` could show you all the files without xattrs. I can double check the code, but offhand do we quote or escape the attribute value in any way for display?

**Comment by etrepum** [comment]
It would be good to look at generally making sure that changes from Apple's version of xattr.tool get backported here first, to avoid diverging behavior if there's a chance that the problem was already solved in a different way there. See also #44

**Comment by devinlane** [comment]
@etrepum Good point. I'll check up on what they do.

**Comment by b-a-t** [comment]
Please, consider that there are attributes, that contain ':' within them, in particular, MacOSX may create those. So, eliminating ':' as a separator would be a good idea.
