### ISSUE TITLE
xattr.get function is not dict-like

### ISSUE THREAD

**Issue by cykerway** [xattr/xattr#54]
This is how a dict's `get` function works:

>   D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.

However, `xattr.get` will raise an exception if the given name doesn't exist, instead of returning `None`.

Do you plan to make its behavior more dict-like?

**Comment by etrepum** [comment]
No immediate plans as this would change the API in a backwards incompatible way. It's also been this way for over a decade and this is the first time it has come up, despite being a bit of a leaky abstraction.
