### ISSUE TITLE
xattr -r option is gone

### ISSUE THREAD

**Issue by mario-grgic** [xattr/xattr#55]
I'm using xattr version 0.9.1 on macOS 10.12.3, which no longer has recursive option -r. So, it is no longer possible to recursively remove extended attributes if target file is a directory.

**Comment by etrepum** [comment]
Must've been an option that Apple has added to their version but has not contributed back to this repository.

**Comment by mario-grgic** [comment]
Interesting, on their own Apple Open Source page they link to this repo:

http://undefined.org/python/#xattr

But, it does indeed look like they had their own implementation.

**Comment by etrepum** [comment]
Their implementation is based on this one, but it diverges occasionally and because it's such a pain in the ass for Apple employees to contribute changes upstream (due to internal legal processes) they often don't bother.
