### ISSUE TITLE
Linux/FreeBSD interoperability

### ISSUE THREAD

**Issue by alistairking** [xattr/xattr#58]
Hey,

I've been trying to get OpenStack Swift running on a combination of Linux and FreeBSD machines, and I've come across a fun problem where Swift will add metadata to a file on linux that once it is rsync'd to FreeBSD, it can no longer access the metadata. 

It seems that this is a namespacing problem -- on Linux the xattr calls expect the attribute name to be fully-qualified (i.e. starting with `user.` in this case), whereas on FreeBSD the namespace is specified as a separate argument (e.g. `EXTATTR_NAMESPACE_USER`).

What this means is that Swift creates/reads metadata with the name `user.swift.metadata` on Linux, but when that file is transferred to FreeBSD and Swift (using this library) tries to get `user.swift.metadata`, FreeBSD treats that like `user.user.swift.metadata` and things thus fail.

I've worked around the problem for now by patching Swift on FreeBSD to use `swift.metadata` instead of `user.swift.metadata`, but it seems that this is perhaps something that could be solved more generally in this library.

I'm pretty new (as in, yesterday) to extended attributes, so please forgive me if I've missed something simple, or if this is a known problem.

Thanks!

**Comment by etrepum** [comment]
The best way would be to write some sort of wrapper for xattr that handles things in a way that's portable across platforms for applications using it. xattr is a relatively low level library, so I think this is probably out of scope. Making platform assumptions may break things for people trying to do platform-specific things with it, and would probably be backwards incompatible for many usages where the default behavior changes due to this.

**Comment by alistairking** [comment]
Ok, I'll add some sort of platform detection to Swift to handle this.
Thanks!

**Comment by jmgurney** [comment]
I'd actually like to reopen this.  I investigated this, and ran into a similar issue.  There is no way to specify FreeBSD system name space in xattr.   I don't know Linux well enough to compare.  Does Linux only have system and user name spaces as well? or are there others?

The reason I would like to ask is that we should detect (or maybe add to the C code) the name space user or system, and do the right thing on FreeBSD.  The biggest issue I see is that it will now introduce a compatibility issue w/ older code that assumes no namespace on FreeBSD, etc.

**Comment by etrepum** [comment]
Seems reasonable to add support for passing that namespace flag on platforms where it is supported. Maybe an explicit function to get the options to pass for a "user namespaced thing" which will prefix "user." on some platforms and use the appropriate namespace flag on others?

What I don't want is to introduce a set of complex "automatic" behaviors that try and work around platform differences at the lowest level that we expose. There ought to be a higher level where this compatibility layer lives.

**Comment by jmgurney** [comment]
Yes, I agree.

Looks like for the lower levels, that adding an option flag to expose selecting USER or SYSTEM will be easiest.  (And a flag saying if the platform needs this or not.)

It looks like Linux has a few more name spaces than FreeBSD does:
       Currently, the security, system, trusted, and user extended attribute
       classes are defined as described below.  Additional classes may be
       added in the future.

Looks like Apple doesn't use name spaces.  Not sure what Sun does.

If added via the options, as the xattr class passes through the options value, we can have users simply provide the flag as needed.  It does mean you'll need two xattr classes for accessing the different attributes, but that isn't a big deal IMO.

It does mean that the compat layer should not live in xattr, as MacOSX uses a different name space mechanism, that you cannot make a truly platform independent version of xattr w/o some underlying knowledge of the platform.  I'll ensure that there is a flag to easily find out if the name space option is available on the current platform.

**Comment by jmgurney** [comment]
Hmm, it also looks like pyxattr compatibility framework does name space prefixing, if NS_USER or NS_SYSTEM is specified, it adds the proper xxx. prefix before passing to the core.  So, I guess when we fix the core part, and pyxattr compat part, you could use that and it would do the correct thing.
