### ISSUE TITLE
Truncated Extended Attributes Values

### ISSUE THREAD

**Issue by ttowncompiled** [xattr/xattr#62]
I've just recently started working with xattr in Python. I'm trying to write a simple script that will recurse through a directory and print the extended attributes of each subdirectory. The expected output is:

```
getfattr -d -m 'ceph.dir.*' /media/cephfs/labs
getfattr: Removing leading '/' from absolute path names
# file: media/cephfs/labs
ceph.dir.entries="21"
ceph.dir.files="3"
ceph.dir.rbytes="332103262384826"
ceph.dir.rctime="1497015869.09352143912"
ceph.dir.rentries="41983401"
ceph.dir.rfiles="41063529"
ceph.dir.rsubdirs="919872"
ceph.dir.subdirs="18"
```
However, with the following code:

```
import xattr
x = xattr.xattr('/media/cephfs/labs')
for k in x.keys():
    print(k, '=', x.get(k))
```

I get the following output:

```
ceph.dir.entries = b'2\x00'
ceph.dir.files = b'\x00'
ceph.dir.subdirs = b'1\x00'
ceph.dir.rentries = b'4198340\x00'
ceph.dir.rfiles = b'4106352\x00'
ceph.dir.rsubdirs = b'91987\x00'
ceph.dir.rbytes = b'33210326238482\x00'
ceph.dir.rctime = b'1497015869.0935214391\x00'
```

As you can see, each value has been truncated and appended with a pad byte.
I've looked over the xattr source code and the only explanation for this that I have seen is that the buffer being passed to ```extattr_get_file``` needs to be increased in size by 1. This may not be right, but it would seem that either ```extattr_get_file``` or ```ffi.buffer(buf)``` are introducing a pad byte into the buffer contents. I could be wrong though.

This is a project for my work so any help with this would be much appreciated.

**Comment by etrepum** [comment]
What are all of the conditions required to reproduce this? Such as: OS, kernel version, Python version, xattr version, file system, and anything else that may be relevant.

**Comment by ttowncompiled** [comment]
Linux dc1srvcephrep01.laureateinstitute.org 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Python 3.5.2

requirements.txt
alembic==0.9.1
cffi==1.10.0
click==6.7
coverage==4.3.4
Flask==0.12.1
Flask-Login==0.4.0
Flask-Migrate==2.0.3
Flask-MySQL==1.4.0
Flask-Script==2.0.5
Flask-SQLAlchemy==2.2
itsdangerous==0.24
Jinja2==2.9.6
ldap3==2.2.3
Mako==1.0.6
MarkupSafe==1.0
pyasn1==0.2.3
pycparser==2.17
PyMySQL==0.7.11
python-editor==1.0.3
requests==2.13.0
SQLAlchemy==1.1.9
Werkzeug==0.12.1
xattr==0.9.2

It's a CEPH file system.
