### ISSUE TITLE
unable to install xattr 0.6.4

### ISSUE THREAD

**Issue by CorneelDragon** [xattr/xattr#64]
When I try to upload an app to the app store I get the following error:

Stripping extended attributes failed. "/usr/bin/xattr -crs /var/folders/t2/fjp18t212bdc6kgb3pjzk81m0000gn/T/XcodeDistPipeline.ZBT/Root/Payload/testvgd.app" exited with a non-zero status. The /usr/bin/xattr tool may be damaged.

When I try to run this tool /usr/bin/xattr from command-line I get: "pkg_resources.DistributionNotFound: The 'xattr==0.6.4' distribution was not found and is required by the application"

Where and how can I add this xattr distribution? I downloaded it from: https://pypi.python.org/pypi/xattr/0.6.4, but when I try to install this, with:
$ python .//xattr-0.6.4/setup.py
I get: 
error: package directory 'xattr' does not exist.

Is there a fix or workaround for this? Thanks!

**Comment by etrepum** [comment]
I’m not sure what the best workaround is but it looks like you’ve damaged your macOS installation. /usr/bin/xattr is the one that ships with the OS. You don’t need to install anything to make it work. You may have deleted some system files or perhaps have some environment variables set that are influencing the module loading for that tool.
