### ISSUE TITLE
Any chance for Python 3.6 support on PyPI?

### ISSUE THREAD

**Issue by justvanrossum** [xattr/xattr#65]
There's some demand for xattr over at fonttools/fonttools#1144

**Comment by etrepum** [comment]
sure, should be just a build matrix update, will look into it

**Comment by etrepum** [comment]
I've been poking at it for a while but Travis-CI is *very* backlogged on OS X infrastructure so it takes a day or two to run a build. I think we're close but we'll see when it finishes. https://travis-ci.org/xattr/xattr

**Comment by etrepum** [comment]
The 0.9.3 release has a wheel for 3.6
