### ISSUE TITLE
Multiple MOSX file "Color" labels?

### ISSUE THREAD

**Issue by bschollnick** [xattr/xattr#83]
I've found code that uses Xattr to display the color label from a MOSX file.  But later versions of the OS can have multiple labels.  (eg Grey, Blue, Red)

This is the code that I'm using right now.

from xattr import xattr
from struct import unpack
import sys

colornames = {
    0: 'none',
    1: 'gray',
    2: 'green',
    3: 'purple',
    4: 'blue',
    5: 'yellow',
    6: 'red',
    7: 'orange',
}

#attrs = xattr('./test.cpp')
attrs = xattr(sys.argv[1])
try:
    finder_attrs = attrs[u'com.apple.FinderInfo']
    flags = unpack(32*'B', finder_attrs)
    color = flags[9] >> 1 & 7
    print (flags)
except KeyError:
    color = 0

print (colornames[color])

For example, I placed Grey and Yellow (1, 5) on the file, and the value I'm seeing in flags[9] is Decimal 10.  

Does xattr support multiple labels?  And if so, can someone point me in the right direction to decode the multiple labels?

**Comment by etrepum** [comment]
I’m sure it does but I’m not familiar with how they’re stored. xattr is quite low level. 

I would recommend searching for some documentation on how these are stored and if you can’t find any you can use iteratively use finder to set multiple labels and then inspect it’s attributes until you can deduce how it works.

**Comment by solarkraft** [comment]
Check this out:

[Inside Finder Tags](https://eclecticlight.co/2017/12/27/inside-finder-tags/)

[xattr: com.apple.metadata:_kMDItemUserTags, Finder tags](https://eclecticlight.co/2017/12/27/xattr-com-apple-metadata_kmditemusertags-finder-tags/)

**Comment by RhetTbull** [comment]
See also [osxmetadata](https://github.com/RhetTbull/osxmetadata)
