### ISSUE TITLE
would you accept a windows *port* if I write it?

### ISSUE THREAD

**Issue by petersilva** [xattr/xattr#84]
We all know extended attributes are not supported on windows.
However there is a windows thing called Alternate Data Streams.
I could use "https://github.com/RobinDavid/pyADS" to write extended attributes to 
an alternate data stream as a JSON (say, call it x.json) and that way it would *work* in that
it would install and work with itself ( the get and set methods would function)  on Windows, 
even if no other programs would know about their existence.

I'm doing this for one project to work around the non-portability of xattr itself.  Is that something you would want in xattr. I see there is #17, and I'm guessing there are many others who were bit.
I'll write the code if people are, in principle, OK with it.  but if they say something like *We are just implementing an non-portable interface, and don't want anything else confusing things* I won't bother.

**Comment by etrepum** [comment]
xattr wraps a specific low level filesystem interface, I’m not sure it makes sense to have it do something quite different on Windows. For the problem you’re trying to solve I think the ideal solution would be to have two other packages, one to handle the Windows specifics, and another package that will import xattr or the Windows package and do something higher level and more domain specific with whatever is available (probably also with a third fallback for when extended attributes are not available). 

That said, if there’s a clear standard for “this is how people encode BSD/Linux style extended attributes on Windows”, then it would be worth considering that. Does WSL support them? If it does, then I would accept an implementation that’s compatible with whatever WSL does.

**Comment by jgstew** [comment]
Here is related info about xattr and WSL on Windows:
- https://github.com/sublimehq/sublime_text/issues/1471

**Comment by petersilva** [comment]
Since folks are asking, I ended up using this module and putting a platform abstraction layer in front of it.
( https://github.com/MetPX/sarracenia/blob/v03_wip/sarracenia/filemetadata.py )
This layer uses ADS on Windows, and extended attributes on linux/unix.  it's embedded in my other project, if there is interest, I supposed I could put it in it's own package, or you could add it to this module... dunno.

**Comment by jgstew** [comment]
@petersilva does it read and write to ADS in the same way as WSL? it would be ideal if it were compatible so that you could run something on linux that saves to xattr in WSL then read it back with the same project running on windows.
