### ISSUE TITLE
Running tests sometimes fail for xattr 0.9.7

### ISSUE THREAD

**Issue by huangtianhua** [xattr/xattr#97]
The tests fail sometimes for xattr 0.9.7, no idea about this, could somebody help me?

[   51s] ============================= test session starts ==============================
[   51s] platform linux -- Python 3.7.9, pytest-3.6.4, py-1.5.4, pluggy-0.6.0
[   51s] rootdir: /home/abuild/rpmbuild/BUILD/xattr-0.9.7, inifile:
[   51s] collected 15 items
[   51s] 
[   51s] xattr/tests/test_xattr.py FF.sFFF.sFFF.sF                                [100%]
[   51s] 
[   51s] =================================== FAILURES ===================================
[   51s] _____________________ TestFile.test_attr_fs_encoding_ascii _____________________
[   51s] 
[   51s] self = <xattr.tests.test_xattr.TestFile testMethod=test_attr_fs_encoding_ascii>
[   51s] 
[   51s]     def test_attr_fs_encoding_ascii(self):
[   51s]         xattr.compat.fs_encoding = 'US-ASCII'
[   51s]         if sys.version_info[0] < 3:
[   51s]             with self.assertRaises(UnicodeEncodeError):
[   51s]                 self._test_attr()
[   51s]         else:
[   51s] >           self._test_attr()
[   51s] 
[   51s] xattr/tests/test_xattr.py:29: 
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] xattr/tests/test_xattr.py:60: in _test_attr
[   51s]     x['user.sopal'] = b'foo'
[   51s] xattr/__init__.py:112: in __setitem__
[   51s]     self.set(item, value)
[   51s] xattr/__init__.py:78: in set
[   51s]     return self._call(_setxattr, _fsetxattr, name, value, 0, options | self.options)
[   51s] xattr/__init__.py:58: in _call
[   51s]     return fd_func(self.value, *args)
[   51s] xattr/lib.py:93: in _fsetxattr
[   51s]     raise error()
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] 
[   51s] path = None
[   51s] 
[   51s]     def error(path=None):
[   51s]         errno = ffi.errno
[   51s]         strerror = os.strerror(ffi.errno)
[   51s]         if path:
[   51s]             raise IOError(errno, strerror, path)
[   51s]         else:
[   51s] >           raise IOError(errno, strerror)
[   51s] E           OSError: [Errno 95] Operation not supported
[   51s] 
[   51s] xattr/lib.py:35: OSError
[   51s] ____________________ TestFile.test_attr_fs_encoding_unicode ____________________
[   51s] 
[   51s] self = <xattr.tests.test_xattr.TestFile testMethod=test_attr_fs_encoding_unicode>
[   51s] 
[   51s]     def test_attr_fs_encoding_unicode(self):
[   51s]         # Not using setlocale(LC_ALL, ..) to set locale because
[   51s]         # sys.getfilesystemencoding() implementation falls back
[   51s]         # to user's preferred locale by calling setlocale(LC_ALL, '').
[   51s]         xattr.compat.fs_encoding = 'UTF-8'
[   51s] >       self._test_attr()
[   51s] 
[   51s] xattr/tests/test_xattr.py:21: 
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] xattr/tests/test_xattr.py:60: in _test_attr
[   51s]     x['user.sopal'] = b'foo'
[   51s] xattr/__init__.py:112: in __setitem__
[   51s]     self.set(item, value)
[   51s] xattr/__init__.py:78: in set
[   51s]     return self._call(_setxattr, _fsetxattr, name, value, 0, options | self.options)
[   51s] xattr/__init__.py:58: in _call
[   51s]     return fd_func(self.value, *args)
[   51s] xattr/lib.py:93: in _fsetxattr
[   51s]     raise error()
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] 
[   51s] path = None
[   51s] 
[   51s]     def error(path=None):
[   51s]         errno = ffi.errno
[   51s]         strerror = os.strerror(ffi.errno)
[   51s]         if path:
[   51s]             raise IOError(errno, strerror, path)
[   51s]         else:
[   51s] >           raise IOError(errno, strerror)
[   51s] E           OSError: [Errno 95] Operation not supported
[   51s] 
[   51s] xattr/lib.py:35: OSError
[   51s] _____________________________ TestFile.test_update _____________________________
[   51s] 
[   51s] self = <xattr.tests.test_xattr.TestFile testMethod=test_update>
[   51s] 
[   51s]     def test_update(self):
[   51s]         x = xattr.xattr(self.tempfile)
[   51s]         attrs = {
[   51s]             'user.test.key1': b'test_value1',
[   51s]             'user.test.key2': b'test_value2'
[   51s]         }
[   51s] >       x.update(attrs)
[   51s] 
[   51s] xattr/tests/test_xattr.py:37: 
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] xattr/__init__.py:143: in update
[   51s]     self[k] = v
[   51s] xattr/__init__.py:112: in __setitem__
[   51s]     self.set(item, value)
[   51s] xattr/__init__.py:78: in set
[   51s]     return self._call(_setxattr, _fsetxattr, name, value, 0, options | self.options)
[   51s] xattr/__init__.py:58: in _call
[   51s]     return fd_func(self.value, *args)
[   51s] xattr/lib.py:93: in _fsetxattr
[   51s]     raise error()
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] 
[   51s] path = None
[   51s] 
[   51s]     def error(path=None):
[   51s]         errno = ffi.errno
[   51s]         strerror = os.strerror(ffi.errno)
[   51s]         if path:
[   51s]             raise IOError(errno, strerror, path)
[   51s]         else:
[   51s] >           raise IOError(errno, strerror)
[   51s] E           OSError: [Errno 95] Operation not supported
[   51s] 
[   51s] xattr/lib.py:35: OSError
[   51s] _____________________ TestDir.test_attr_fs_encoding_ascii ______________________
[   51s] 
[   51s] self = <xattr.tests.test_xattr.TestDir testMethod=test_attr_fs_encoding_ascii>
[   51s] 
[   51s]     def test_attr_fs_encoding_ascii(self):
[   51s]         xattr.compat.fs_encoding = 'US-ASCII'
[   51s]         if sys.version_info[0] < 3:
[   51s]             with self.assertRaises(UnicodeEncodeError):
[   51s]                 self._test_attr()
[   51s]         else:
[   51s] >           self._test_attr()
[   51s] 
[   51s] xattr/tests/test_xattr.py:29: 
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] xattr/tests/test_xattr.py:60: in _test_attr
[   51s]     x['user.sopal'] = b'foo'
[   51s] xattr/__init__.py:112: in __setitem__
[   51s]     self.set(item, value)
[   51s] xattr/__init__.py:78: in set
[   51s]     return self._call(_setxattr, _fsetxattr, name, value, 0, options | self.options)
[   51s] xattr/__init__.py:60: in _call
[   51s]     return name_func(self.value, *args)
[   51s] xattr/lib.py:82: in _setxattr
[   51s]     raise error(path)
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] 
[   51s] path = b'/tmp/tmpoj3r34hv'
[   51s] 
[   51s]     def error(path=None):
[   51s]         errno = ffi.errno
[   51s]         strerror = os.strerror(ffi.errno)
[   51s]         if path:
[   51s] >           raise IOError(errno, strerror, path)
[   51s] E           OSError: [Errno 95] Operation not supported: b'/tmp/tmpoj3r34hv'
[   51s] 
[   51s] xattr/lib.py:33: OSError
[   51s] ____________________ TestDir.test_attr_fs_encoding_unicode _____________________
[   51s] 
[   51s] self = <xattr.tests.test_xattr.TestDir testMethod=test_attr_fs_encoding_unicode>
[   51s] 
[   51s]     def test_attr_fs_encoding_unicode(self):
[   51s]         # Not using setlocale(LC_ALL, ..) to set locale because
[   51s]         # sys.getfilesystemencoding() implementation falls back
[   51s]         # to user's preferred locale by calling setlocale(LC_ALL, '').
[   51s]         xattr.compat.fs_encoding = 'UTF-8'
[   51s] >       self._test_attr()
[   51s] 
[   51s] xattr/tests/test_xattr.py:21: 
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] xattr/tests/test_xattr.py:60: in _test_attr
[   51s]     x['user.sopal'] = b'foo'
[   51s] xattr/__init__.py:112: in __setitem__
[   51s]     self.set(item, value)
[   51s] xattr/__init__.py:78: in set
[   51s]     return self._call(_setxattr, _fsetxattr, name, value, 0, options | self.options)
[   51s] xattr/__init__.py:60: in _call
[   51s]     return name_func(self.value, *args)
[   51s] xattr/lib.py:82: in _setxattr
[   51s]     raise error(path)
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] 
[   51s] path = b'/tmp/tmpcd5cj275'
[   51s] 
[   51s]     def error(path=None):
[   51s]         errno = ffi.errno
[   51s]         strerror = os.strerror(ffi.errno)
[   51s]         if path:
[   51s] >           raise IOError(errno, strerror, path)
[   51s] E           OSError: [Errno 95] Operation not supported: b'/tmp/tmpcd5cj275'
[   51s] 
[   51s] xattr/lib.py:33: OSError
[   51s] _____________________________ TestDir.test_update ______________________________
[   51s] 
[   51s] self = <xattr.tests.test_xattr.TestDir testMethod=test_update>
[   51s] 
[   51s]     def test_update(self):
[   51s]         x = xattr.xattr(self.tempfile)
[   51s]         attrs = {
[   51s]             'user.test.key1': b'test_value1',
[   51s]             'user.test.key2': b'test_value2'
[   51s]         }
[   51s] >       x.update(attrs)
[   51s] 
[   51s] xattr/tests/test_xattr.py:37: 
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] xattr/__init__.py:143: in update
[   51s]     self[k] = v
[   51s] xattr/__init__.py:112: in __setitem__
[   51s]     self.set(item, value)
[   51s] xattr/__init__.py:78: in set
[   51s]     return self._call(_setxattr, _fsetxattr, name, value, 0, options | self.options)
[   51s] xattr/__init__.py:60: in _call
[   51s]     return name_func(self.value, *args)
[   51s] xattr/lib.py:82: in _setxattr
[   51s]     raise error(path)
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] 
[   51s] path = b'/tmp/tmp57mn74fl'
[   51s] 
[   51s]     def error(path=None):
[   51s]         errno = ffi.errno
[   51s]         strerror = os.strerror(ffi.errno)
[   51s]         if path:
[   51s] >           raise IOError(errno, strerror, path)
[   51s] E           OSError: [Errno 95] Operation not supported: b'/tmp/tmp57mn74fl'
[   51s] 
[   51s] xattr/lib.py:33: OSError
[   51s] ______________ TestFileWithSurrogates.test_attr_fs_encoding_ascii ______________
[   51s] 
[   51s] self = <xattr.tests.test_xattr.TestFileWithSurrogates testMethod=test_attr_fs_encoding_ascii>
[   51s] 
[   51s]     def test_attr_fs_encoding_ascii(self):
[   51s]         xattr.compat.fs_encoding = 'US-ASCII'
[   51s]         if sys.version_info[0] < 3:
[   51s]             with self.assertRaises(UnicodeEncodeError):
[   51s]                 self._test_attr()
[   51s]         else:
[   51s] >           self._test_attr()
[   51s] 
[   51s] xattr/tests/test_xattr.py:29: 
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] xattr/tests/test_xattr.py:60: in _test_attr
[   51s]     x['user.sopal'] = b'foo'
[   51s] xattr/__init__.py:112: in __setitem__
[   51s]     self.set(item, value)
[   51s] xattr/__init__.py:78: in set
[   51s]     return self._call(_setxattr, _fsetxattr, name, value, 0, options | self.options)
[   51s] xattr/__init__.py:58: in _call
[   51s]     return fd_func(self.value, *args)
[   51s] xattr/lib.py:93: in _fsetxattr
[   51s]     raise error()
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] 
[   51s] path = None
[   51s] 
[   51s]     def error(path=None):
[   51s]         errno = ffi.errno
[   51s]         strerror = os.strerror(ffi.errno)
[   51s]         if path:
[   51s]             raise IOError(errno, strerror, path)
[   51s]         else:
[   51s] >           raise IOError(errno, strerror)
[   51s] E           OSError: [Errno 95] Operation not supported
[   51s] 
[   51s] xattr/lib.py:35: OSError
[   51s] _____________ TestFileWithSurrogates.test_attr_fs_encoding_unicode _____________
[   51s] 
[   51s] self = <xattr.tests.test_xattr.TestFileWithSurrogates testMethod=test_attr_fs_encoding_unicode>
[   51s] 
[   51s]     def test_attr_fs_encoding_unicode(self):
[   51s]         # Not using setlocale(LC_ALL, ..) to set locale because
[   51s]         # sys.getfilesystemencoding() implementation falls back
[   51s]         # to user's preferred locale by calling setlocale(LC_ALL, '').
[   51s]         xattr.compat.fs_encoding = 'UTF-8'
[   51s] >       self._test_attr()
[   51s] 
[   51s] xattr/tests/test_xattr.py:21: 
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] xattr/tests/test_xattr.py:60: in _test_attr
[   51s]     x['user.sopal'] = b'foo'
[   51s] xattr/__init__.py:112: in __setitem__
[   51s]     self.set(item, value)
[   51s] xattr/__init__.py:78: in set
[   51s]     return self._call(_setxattr, _fsetxattr, name, value, 0, options | self.options)
[   51s] xattr/__init__.py:58: in _call
[   51s]     return fd_func(self.value, *args)
[   51s] xattr/lib.py:93: in _fsetxattr
[   51s]     raise error()
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] 
[   51s] path = None
[   51s] 
[   51s]     def error(path=None):
[   51s]         errno = ffi.errno
[   51s]         strerror = os.strerror(ffi.errno)
[   51s]         if path:
[   51s]             raise IOError(errno, strerror, path)
[   51s]         else:
[   51s] >           raise IOError(errno, strerror)
[   51s] E           OSError: [Errno 95] Operation not supported
[   51s] 
[   51s] xattr/lib.py:35: OSError
[   51s] ______________________ TestFileWithSurrogates.test_update ______________________
[   51s] 
[   51s] self = <xattr.tests.test_xattr.TestFileWithSurrogates testMethod=test_update>
[   51s] 
[   51s]     def test_update(self):
[   51s]         x = xattr.xattr(self.tempfile)
[   51s]         attrs = {
[   51s]             'user.test.key1': b'test_value1',
[   51s]             'user.test.key2': b'test_value2'
[   51s]         }
[   51s] >       x.update(attrs)
[   51s] 
[   51s] xattr/tests/test_xattr.py:37: 
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] xattr/__init__.py:143: in update
[   51s]     self[k] = v
[   51s] xattr/__init__.py:112: in __setitem__
[   51s]     self.set(item, value)
[   51s] xattr/__init__.py:78: in set
[   51s]     return self._call(_setxattr, _fsetxattr, name, value, 0, options | self.options)
[   51s] xattr/__init__.py:58: in _call
[   51s]     return fd_func(self.value, *args)
[   51s] xattr/lib.py:93: in _fsetxattr
[   51s]     raise error()
[   51s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   51s] 
[   51s] path = None
[   51s] 
[   51s]     def error(path=None):
[   51s]         errno = ffi.errno
[   51s]         strerror = os.strerror(ffi.errno)
[   51s]         if path:
[   51s]             raise IOError(errno, strerror, path)
[   51s]         else:
[   51s] >           raise IOError(errno, strerror)
[   51s] E           OSError: [Errno 95] Operation not supported
[   51s] 
[   51s] xattr/lib.py:35: OSError
[   51s] ================ 9 failed, 3 passed, 3 skipped in 0.80 seconds =================

**Comment by etrepum** [comment]
It looks like you are running the tests on a platform or file system that does not support extended attributes, or the file system is mounted in a way that does not permit their use.

**Comment by huangtianhua** [comment]
@etrepum Thanks. Then how I can know whether the platform or the file system support extended attributes?

**Comment by etrepum** [comment]
The architecture is not relevant. The operating system, the filesystem, and how the filesystem is mounted are what determine whether or not extended attributes are supported.

**Comment by etrepum** [comment]
For more information see the relevant documentation for your operating system. There will likely be a man page for xattr.
