### ISSUE TITLE
On Monterey getting `TypeError: main() missing 1 required positional argument: 'argv'`

### ISSUE THREAD

**Issue by ni-dschiller** [xattr/xattr#99]
```bash
 ~ % xattr
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/xattr", line 8, in <module>
    sys.exit(main())
TypeError: main() missing 1 required positional argument: 'argv'
 ~ % 
```

**Comment by etrepum** [comment]
This can be fixed by updating to v0.9.9 which is in the process of being released, or downgrading to v0.9.7.

**Comment by iotY** [comment]
@etrepum I have similar on Manjaro with 0.9.6 or .7 or .8 or .9

`Traceback (most recent call last):
  File "/usr/bin/xattr", line 33, in <module>
    sys.exit(load_entry_point('xattr==0.9.7', 'console_scripts', 'xattr')())
TypeError: main() missing 1 required positional argument: 'argv'
`

I also tried downgrading python but got halted with ImportError: libffi.so.7... (Remember xattr worked fine in August)

**Comment by iotY** [comment]
@etrepum EDIT: doesn't work if installed with `sudo python setup.py install`, but fine OK if downgraded to python-xattr-0.9.7-5-x86_64.pkg.tar.zst via Manjaro/Pamac (!)

Guess everything will be ok with upcomming Pamac 0.9.9

btw, thanks again for your work; it brings android/Treble to miracle: https://github.com/phhusson/sas-creator/blob/master/lite-adapter.sh

**Comment by etrepum** [comment]
I'm only able to reproduce this issue with xattr 0.9.8. If you are experiencing the issue with other versions, you may not have installed it appropriately.
